[2022-06-04 08:10:58.5440] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <Zathura (Ubuntu).lnk>

[2022-06-04 08:11:04.6207] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <TeXdoctk (Ubuntu).lnk>

[2022-06-04 08:11:10.6597] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <Xournal++ (Ubuntu).lnk>

[2022-06-04 08:11:16.6933] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <Inkscape (Ubuntu).lnk>

[2022-06-04 08:11:22.7344] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <ImageMagick (color depth=q16) (Ubuntu).lnk>

[2022-06-04 08:11:28.7832] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <Xournal (Ubuntu).lnk>

[2022-06-04 08:11:34.8585] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <WSLView (Ubuntu).lnk>

[2022-06-04 08:11:40.8980] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <kitty (Ubuntu).lnk>

[2022-06-04 09:10:22.4915] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <Zathura (Ubuntu).lnk>

[2022-06-04 09:10:28.5514] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <TeXdoctk (Ubuntu).lnk>

[2022-06-04 09:10:34.5883] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <Xournal++ (Ubuntu).lnk>

[2022-06-04 09:10:40.6171] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <Inkscape (Ubuntu).lnk>

[2022-06-04 09:10:46.6625] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <ImageMagick (color depth=q16) (Ubuntu).lnk>

[2022-06-04 09:10:52.7051] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <Xournal (Ubuntu).lnk>

[2022-06-04 09:10:58.7367] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <WSLView (Ubuntu).lnk>

[2022-06-04 09:11:04.7684] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <kitty (Ubuntu).lnk>

[2022-06-04 11:04:08.4100] [INFO] [C:\a\_work\1\s\src\modules\launcher\PowerLauncher\SettingsReader.cs::68]
Settings were changed. Read settings.

[2022-06-04 11:04:08.4817] [INFO] [C:\a\_work\1\s\src\modules\launcher\PowerLauncher\SettingsReader.cs::88]
Successfully read new settings. retryCount=1

[2022-06-04 12:42:41.7445] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.Getstarted
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:42:41.7651] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.Getstarted
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:42:41.7704] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.Getstarted
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:43:13.2250] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsFeedbackHub
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:43:13.2362] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsFeedbackHub
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:43:13.2362] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsFeedbackHub
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:43:43.4305] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.MixedReality.Portal
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:43:43.4405] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.MixedReality.Portal
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:43:43.4405] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.MixedReality.Portal
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:44:27.3860] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.XboxGamingOverlay
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:44:27.3950] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.XboxGamingOverlay
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:44:27.3950] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.XboxGamingOverlay
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:45:03.8452] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.XboxIdentityProvider
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:45:03.8452] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.XboxIdentityProvider
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:45:03.8641] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.XboxIdentityProvider
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:45:20.7824] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.XboxGameOverlay
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:45:20.7824] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.XboxGameOverlay
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2022-06-04 12:45:20.7824] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::59]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
		Possible interpretation of the error: Exception Microsoft.XboxGameOverlay
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|20_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


